### ISSUE TITLE
Refiner steps change miscalculation?

### ISSUE THREAD

**Issue by sashasubbbb** [Carzit/sd-webui-samplers-scheduler-for-v1.6#3]
There seems to be a problem with using refiner, model switching actual step count does not correlate with "switch at" step count when using seniorious sampler.

**Comment by Carzit** [comment]
I am not very familiar with SDXL, so this code implementation is simply applied to the t2i part of SD1.5. I didn't consider the refiner of SDXL.    
Actually, there is still a lot of work to do, such as somethong about hires.fix, the i2i part and adding more samplers like DDIM and UniPC.  Compatibility with the additional features of SDXL will be considered after completing these work.  
Or you may commit PR if you can bear my awful code and handle the problem. QAQ  
A TODO list will be added to README if I have time.
